# Generated by Django 5.2.17 on 2026-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(choices=[('House Removal', 'House Removal'), ('Interstate Move', 'Interstate Move'), ('Office Relocation', 'Office Relocation'), ('Small Pick & Drop', 'Small Pick & Drop'), ('Furniture Assembly', 'Furniture Assembly'), ('Rubbish Removal', 'Rubbish Removal'), ('Second Hand Appliances', 'Second-Hand Appliances')], max_length=50)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('move_size', models.CharField(choices=[('Single Item / Few Items', 'Single Item / Few Items'), ('1 Bedroom Apartment', '1 Bedroom Apartment'), ('2 Bedroom Apartment / House', '2 Bedroom Apartment / House'), ('3+ Bedroom House', '3+ Bedroom House'), ('Office / Commercial', 'Office / Commercial')], max_length=50)),
                ('move_date', models.DateField(blank=True, null=True)),
                ('move_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
